name: Go Module Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build and Test
        run: |
          go mod tidy
          go test ./...

      - name: Publish Go Module
        run: |
          git tag $(git describe --tags --abbrev=0)
          git push origin --tags
